# Generated by Django 3.0.6 on 2022-01-22 05:44

import Pharmacy.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0002_auto_20220113_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, default='Default', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pharmaceuticalcategory',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pharmaceuticals',
            name='custom_id',
            field=models.CharField(blank=True, default=Pharmacy.utils.random_string, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pharmaceuticals',
            name='product_measurement',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pharmaceuticaltype',
            name='name',
            field=models.CharField(default='Default', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='purchase_ref',
            field=models.CharField(blank=True, default=Pharmacy.utils.random_string, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='procurementlist',
            name='purchase_ref',
            field=models.CharField(blank=True, default=Pharmacy.utils.random_string, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='procurementlist',
            name='supplier',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_ref',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='saleslist',
            name='customer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='saleslist',
            name='sales_ref',
            field=models.CharField(blank=True, default=Pharmacy.utils.random_string, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='saleslist',
            name='sales_type',
            field=models.CharField(blank=True, choices=[('Retail', 'Retail'), ('Wholesale', 'Wholesale')], default='Retail', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(blank=True, default='Default', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
